### ISSUE TITLE
Landing Page Integration

### ISSUE THREAD

**Issue by Uot-Project1-Group07** [Uot-Project1-Group07/project1-group07#3]
Anagha's Jokes Container
Anagha's Jokes Javascript
Manjula Landing Page
Raj's Login Modal
Raj's Inspiration API
Kri's Covid recovered numbers
Anagha's Chat integration

**Comment by Uot-Project1-Group07** [comment]
Anagha's Jokes Containert - COMPLETED
Anagha's Jokes Javascript - COMPLETED

**Comment by Uot-Project1-Group07** [comment]
Manjula Landing Page - COMPLETED

**Comment by esroleo** [comment]
Completed.
